### ISSUE TITLE
Cannot read property for 3rd party types

### ISSUE THREAD

**Issue by rahmatrhd** [Typescript-TDD/ts-auto-mock#104]
I am on a Google Apps Script project using typescript and use `@types/google-apps-script` for the types. I want to create a mock object to test an apps script object locally.

```ts
const mockSpreadsheet = createMock<GoogleAppsScript.Spreadsheet.Spreadsheet>();
```

but when running the test (with `mocha`) I got this error message:

```zsh
> npx mocha -r ./tsnode.js **/*.spec.ts

Cannot read property 'kind' of undefined
```

Previously I tried to use an interface I created by myself at it worked. But when I am using interface from apps script (`GoogleAppsScript.Spreadsheet.Spreadsheet`) it returned an error. I am not sure this is the problem with ts-auto-mock or the 3rd party types

**Comment by uittorio** [comment]
@rahmatrhd Hi. I've investigated the issue and I've found out that EnumDeclaration in namespace behave differently.
```ts

declare namespace NameSpace {
    interface WithEnum {
        a: InsideNameSpace;
        b: InsideNameSpaceValue;
        c: OutsideNameSpace;
    }

    enum InsideNameSpaceValue {
        A = '1',
        B = '2',
    }

    enum InsideNameSpace {
        A,
        B
    }
}
```

I'll work on the fix later today or this weekend. Is nothing major :)

Thanks for the feedback

**Comment by uittorio** [comment]
#106 will fix this issue :). I'll let you know when is merged and published. @rahmatrhd  Thanks again  for the feedback.

**Comment by uittorio** [comment]
new version released :). Feel free to close the bug once you are happy with it!

**Comment by rahmatrhd** [comment]
Awesome!! It's working now after I updated to `1.4.1`.
Thanks a lot for the help, @uittorio 🎉
