### ISSUE TITLE
Is there a minimum node version requirement for `ts-auto-mock`?

### ISSUE THREAD

**Issue by muk-ai** [Typescript-TDD/ts-auto-mock#1134]
### Subject of the issue

Is there a minimum node version requirement for `ts-auto-mock`?

### Your environment
* ts-auto-mock version: 3.6.1
* typescript version: 4.4.4
* node version: v14.17.3

### Steps to reproduce

```
$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error ts-auto-mock@3.6.1: The engine "node" is incompatible with this module. Expected version ">=16.x.x". Got "14.17.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I did not get this error in ts-auto-mock `3.6.0`.
Do I have no choice but to upgrade node?

**Comment by uittorio** [comment]
hi, this is a regression since the last update. I was not expecting to impact the production one!! I will revert the change. for the time being, keep using version 3.6.0!  I will keep supporting version 14 for a while longer.

Also, keep looking at this table from node js to see which versions they support https://nodejs.org/en/about/releases/

**Comment by muk-ai** [comment]
Thanks for supporting version 14.
And thank you for maintaining excellent software.

**Comment by uittorio** [comment]
@muk-ai this release is now in progress, 

I've also added more tests during the ci to cover lts/fermium and lts/gallium!! 

https://github.com/Typescript-TDD/ts-auto-mock/pull/1136

You will see a new release soon!

**Comment by uittorio** [comment]
here you go, feel free to close the bug when you are happy with that. https://typescripttdd.slack.com/archives/C014RPFH8EQ/p1651858775145709

**Comment by muk-ai** [comment]
Thank you very much, it worked perfectly.
