### ISSUE TITLE
does it support @swc/jest?

### ISSUE THREAD

**Issue by mystyle2006** [Typescript-TDD/ts-auto-mock#1224]
**Is your feature request related to a problem?**
we test out jest with @swc/jest as ts-jest keep slow.
does ts-auto-mock supoort @swc/jest? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uittorio** [comment]
Hi! 👋 

No, ts auto mock does no support it but swc provides a plugin system. We could make it work. Happy to review a PR
