### ISSUE TITLE
does it support Vitest ?

### ISSUE THREAD

**Issue by kawamataryo** [Typescript-TDD/ts-auto-mock#1271]
**Is your feature request related to a problem?**

Thanks for developing a very cool library.
This library has made the testing environment of my project so much better!

Can I get ts-auto-mock to work with [Vitest](https://vitest.dev/)?

vitest is a very fast-running testing framework.
I am currently considering migration from ts-jest to vitest.
However, I am having trouble getting through the tests that depend on ts-auto-mock.
I would be very happy if you could give me a solution.

**Comment by MasatoDev** [comment]
Hi! @kawamataryo 

Not this tool, but we have released a tool to create test data from type, interface, and class.
Since it outputs the actual code, the behavior is independent of the environment.

https://github.com/MasatoDev/boostest

Please take a look if you like.
