### ISSUE TITLE
Add support for babel (Maybe)

### ISSUE THREAD

**Issue by uittorio** [Typescript-TDD/ts-auto-mock#129]
When babel is used in combination with Typescript is not possible to use ts-auto-mock because the code is compiled by Babel. 

This issue opened in typescirpt-is explain the scenario (https://github.com/woutervh-/typescript-is/issues/18)

A possible solution would be to write another plugin for babel

I've opened this issue as a placeholder, I'm not sure yet how much work is involved to achieve this.

**Comment by Pmyl** [comment]
Two questions:
- what is the benefit of having Babel?
- is this benefit needed (and used) in the automation tests run?

**Comment by uittorio** [comment]
You can use babel-jest instead of ts-jest to run your test. Babel is used in combination of typescript to benefit from the type safety.

**Comment by uittorio** [comment]
We don't have any plan to create a transformer for babel.

**Comment by imjordanxd** [comment]
Any chance of reviving this? I've found TS-Jest to become unbearably slow. Setting `isolatedModules: true` unfortunately breaks the tests.

**Comment by uittorio** [comment]
Hi @imjordanxd! Sorry for the late reply! I think we can improve the configuration to make it faster! Can you share your project so I can see what we can do?

As we mentioned before babel ts auto mock would be a completely different project!

**Comment by imjordanxd** [comment]
Hey @uittorio, I'm working on a private project so unfortunately, I can't share it. Are there any details you require? At a very high level, I'm using the basic installation [here](https://typescript-tdd.github.io/ts-auto-mock/installation#jest--ts-jest--ttypescript) to test my React application with `testing-library`.

**Comment by imjordanxd** [comment]
Hi @uittorio, just following up on this to see if you have any suggestions?

**Comment by jonas2727** [comment]
@Pmyl 
I can tell you a benefit. Relay requires the babel-plugin-relay to work (replaces GraphQL-tags with compiled artifacts).
And for unittesting fragments, the plugin is required to also transpile the test code. Thus Relay and ts-auto-mock cannot be used together which is really sad
