### ISSUE TITLE
Passing a generic type to createMock throws weird error in a wrong place!

### ISSUE THREAD

**Issue by rostamiani** [Typescript-TDD/ts-auto-mock#1395]
I'm trying to pass interface to createMock using a generic parameter and it raises a weird error on a weird place!

For example this is my test:
```ts
describe('Channel Service', () => {
  // let mok: MockedServices;
  // const mokChannels = createMockList<Channel>(10);
  // const mokChannelsDto = createMock<GetChannelsDto>();

  function mockIt<U extends object>() {
    return createMock<U>();
  }

  const testMok = mockIt<User>();
  console.log(testMok);

  console.log('Something lo be logged!!!');
});
```
It generates this error on a wrong line!:
```
    ReferenceError: t is not defined
```
But there is no `t` variable in my code
This is the full error:

![image](https://user-images.githubusercontent.com/1157108/188863793-bae6b2b5-6560-4ae9-be4b-0dfb62c9ff25.png)

**Comment by uittorio** [comment]
That is correct! Ts auto mock needs to find a CreateMock with a type! It could be that is possible to achieve what you are descrivibing but it requires some investigation and re work!

**Comment by uittorio** [comment]
I do agree that the error is not useful!
