### ISSUE TITLE
"ts-auto-mock" is not published error

### ISSUE THREAD

**Issue by cesarvspr** [Typescript-TDD/ts-auto-mock#1436]
### "ts-auto-mock" is not published error

I can use the auto mock tool but eslint keeps telling me that 'ts-auto-mock' and 'jest-ts-auto-mock' are not published packages.

Sorry if this is not the right place for this. I tried follow the docs but could no see anything related.

### Your environment
* ts-auto-mock version: 3.6.2
* typescript version: 4.8.4
* node version: v18.4.0
* npm version: 8.12.1

### Steps to reproduce
```typescript
import 'jest-ts-auto-mock';
```

or 

```typescript
import {createMock} from 'ts-auto-mock';
```

### Expected behavior

No error on import raised by eslint.

### Actual behavior

"jest-ts-auto-mock" is not published.eslint

**Comment by uittorio** [comment]
Hi, sorry for the late reply, you might find this useful

https://stackoverflow.com/questions/67551956/node-no-unpublished-import-chai-is-not-published

**Comment by cesarvspr** [comment]
Exactly what I did to fix. Many thanks @uittorio
