### ISSUE TITLE
[Doc improvement] Improve the `ts-jest` configuration in the docs

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#1439]
**Is your feature request related to a problem?**
Defining `ts-jest` under `globals` is deprecated.
The current documentation is still showing this way to configure the dependency, like:
```json
{
	globals: {
    	'ts-jest': {
     	 compiler: `ttypescript`
    	}
 	 }
}
```

**Describe the solution you'd like**
Can you update the docs to use a not deprecated version of the configuration?

**Additional context**
The complete warning is:
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
}
```

**Comment by uittorio** [comment]
Hey, just opened a PR that will also update the docs! thank you for sharing it!
