### ISSUE TITLE
typescript 4.9.3 deprecation warnings

### ISSUE THREAD

**Issue by tobias-jueschke** [Typescript-TDD/ts-auto-mock#1444]
### Subject of the issue
Since updating to typescript version 4.9.3 deprecation warnings are shown during test runs.

### Your environment
* ts-auto-mock version: 3.6.2
* typescript version: 4.9.3
* node version: 16.14.0
* npm version: 8.3.1

### Steps to reproduce
Upgrade the project using ts-auto-mock to typescript version 4.9.3 and run the unit tests using function like createMock<T>().

### Expected behavior
No deprecation warnings are shown like:
`DeprecationWarning: 'createMethodDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
`

### Actual behavior
Deprecation warnings are shown

**Comment by uittorio** [comment]
Hi! thank you for opening the issue. this https://github.com/Typescript-TDD/ts-auto-mock/pull/1447 should fix it!
