### ISSUE TITLE
Support Typescript 5

### ISSUE THREAD

**Issue by hoi4** [Typescript-TDD/ts-auto-mock#1465]
Hi, @uittorio 

Thank you for your invaluable work on this library!

Are there plans to support Typescript 5?

Thank you!

**Comment by uittorio** [comment]
Hey! I can give it a try! Hopefully is not too difficult!

**Comment by uittorio** [comment]
Hey @hoi4 . It looks like we are not in a great position. 

Ts-auto-mock depends on libraries like ts-patch or ttypescript.

ttypescript is not maintaned and ts-patch has a beta version out that I need to try!

ts-patch -> https://github.com/nonara/ts-patch/issues/93

typescript notes -> https://github.com/microsoft/TypeScript/issues/52953

I will update this issue!

**Comment by hoi4** [comment]
I also already migrated our tests to use `ts-patch` instead of `ttypescript` and tried the beta of `ts-patch` (by overwriting the peer dependency `typescript` of `ts-auto-mock` to use `5.0.4`). Unfortunately, `ts-auto-mock` reported that it is not setup correctly. (The same setup works fine with typescript 4.9.5)

**Comment by uittorio** [comment]
good news, I can run it locally with ts-patch in beta!! I need to fix a couple of things but it's promising!

**Comment by uittorio** [comment]
This is the PR, just need to see if it works in different version of node and also add some documentation about ttypescript that is deprecated for typescript 5 and ts-patch that is in beta. https://github.com/Typescript-TDD/ts-auto-mock/pull/1466

**Comment by uittorio** [comment]
I will probably merge it tomorrow morning and then it will be automatically released

**Comment by uittorio** [comment]
You should try ts-auto-mock version 3.7. It has just been released.

I was expecting a new version released (4.0) considering the breaking change but for some reason semantic release didnt work and it  bump to a version minor instead of major!

**Comment by hoi4** [comment]
You are a legend! 🚀 I will try it tomorrow 👍🏻

**Comment by hoi4** [comment]
@uittorio Most of our tests work like a charm with the new version. Thank you the amazingly quick release. 

There seems to be a problem with nested mocks though 🤔 

*Example:*

```typescript
const summaryImages: SummaryImage[] = createMockList<SummaryImage>(2, (index: number) => {
  return {
    id: index,
    source: `source-for-id-${index}`,
  };
});

const test = createMock<Summary>({ summaryImages })
```

The error is `Type 'SummaryImage[]' is not assignable to type 'PartialObjectDeep<SummaryImage[]>`.

**Comment by uittorio** [comment]
Oh thats a shame! Thank you for reporting it! Do you mind just copy this into a new bug? 

I will have a look!
