### ISSUE TITLE
Creating test data independent of environment outside of tsc

### ISSUE THREAD

**Issue by MasatoDev** [Typescript-TDD/ts-auto-mock#1587]
### Subject of the issue

ts-auto-mock only works in certain environments.

Not this tool, but we have released a tool to create test data from type, interface, and class.
Since it outputs the actual code, the behavior is independent of the environment.

https://github.com/MasatoDev/boostest

Please take a look if you like.

**Comment by uittorio** [comment]
I will close this issue because we are not planning any new feature development!

Thanks!
