### ISSUE TITLE
TS error on a specific class mock

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#282]
### Subject of the issue
When using `createMock` on a specific complex class, an error occurred breaking all the tests.

### Your environment
* ts-auto-mock version: 1.5.7
* typescript version: 3.8.3
* node version: 13.5.0
* npm version: 6.14.2
* ttypescript: 1.5.10
* jest-ts-auto-mock: 1.0.11
* jest: 25.2.4
* discord.js: 12.1.1

### Steps to reproduce
```typescript
import { Message } from 'discord.js';

createMock<Message>();
```

You can also checkout the [online version](https://codesandbox.io/s/ts-auto-mock-bug-m50kc) of the problem but note that the tests are not working with the dependencies so this is only to have a look of the dependencies and the test not working.

### StackTrace
```javascript
TypeError: Cannot read property 'declarations' of undefined

at r (node_modules/ts-auto-mock/transformer/index.js:176:21)
at Object.t [as GetDeclarationFromNode] (node_modules/ts-auto-mock/transformer/index.js:172:16)
at node_modules/ts-auto-mock/transformer/index.js:550:38
at Array.forEach (<anonymous>)
at node_modules/ts-auto-mock/transformer/index.js:549:17
at Array.forEach (<anonymous>)
at p (node_modules/ts-auto-mock/transformer/index.js:548:46)
at l (node_modules/ts-auto-mock/transformer/index.js:542:41)
at Object.t.CreateMockFactory (node_modules/ts-auto-mock/transformer/index.js:561:59)
at Object.t.GetTypeReferenceDescriptor (node_modules/ts-auto-mock/transformer/index.js:960:188)
```

### Expected behavior
No error and a mock produced.

### Actual behavior
Error and no mock produced.

### Additional information
Could be related to the [#201 issue](https://github.com/Typescript-TDD/ts-auto-mock/issues/201).

**Comment by C0ZEN** [comment]
> <@U010ZUZQPS4> morning!. I confirm that there is an issue mocking Message. The interface it's actually quite complex.
<sub>[View in Slack](https://typescripttdd.slack.com/archives/CQA8YHKT5/p1585552496036300)</sub>

**Comment by uittorio** [comment]
Hi, good news. I've found the source of the bug.

```declare function TestFn(): new (...args: any[]) => Test ;

// @ts-ignore
class Test extends TestFn() {
  public a: string;
}```

We don`t currently support extending function constructor. 

I've found a fix, just need to add more tests to make sure we are covering all the scenarios.

**Comment by uittorio** [comment]
I've created a branch. Once it's reviewed and merge, a new version will be published :). #296

**Comment by uittorio** [comment]
This is fixed in 1.6.0 :) I'll close for now. Feel free to reopen it if it's still bugged.

**Comment by C0ZEN** [comment]
@uittorio I refactored all the Discord classes with `createMock` and for all the cases this new version is fine.
Thank you for the time and the fix, this is very nice.

**Comment by uittorio** [comment]
Cool! bear in mind that some types are not working in discord.. it will convert to null :) hopefully it will not impact your code
