### ISSUE TITLE
Missing changelog for 2.1.0 version

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#335]
### Subject of the issue
The changelog for the `2.1.0` version is missing.

### Expected behavior
The master CHANGELOG.md should have a release notes for the tag `2.1.0`.

**Note:**
Remember once the CHANGELOG.md updated, the published npm package should also be updated.

**Comment by uittorio** [comment]
Hi @C0ZEN, thanks . The process is completely automated by github actions :) I'll have a look

**Comment by uittorio** [comment]
This is now partially fixed. I'm enforcing to recreating the changelog every time there is a new version. I'll think about when I have more time a better solution

**Comment by C0ZEN** [comment]
@uittorio if you are willing to use semantic release I could provide a PR unless you have a very specific reason to use automated but selfmade versioning.

**Comment by uittorio** [comment]
Yes, I'll be happy to use semantic releases. I was a bit nervous about it when we first started this project but I think now it's mature enough to have automated semantic releases. I am not sure how it will work with breaking changes. Can you still write down breaking changes in the commit message and then it will be reflected in the changelog or we still need something like conventional-changelog?

**Comment by C0ZEN** [comment]
From the moment you think about it when you wrote down your commits everything will be fine, semantic will also handled the breaking changes.
Then it is settle I will provide a PR with semantic release and commitizen configuration.
I will open an issue for that.

**Comment by uittorio** [comment]
Thanks! really appreciate it :)
