### ISSUE TITLE
[Feature] Add a new template to provide a feature request

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#340]
The only possible template when opening an issue is an issue template.
Having a feature request template could be pretty convenient (as I am writing this for example, I do not have any guidelines on how you would like me to write it down).
This is always more welcoming to have a structure especially when opening an issue in a new repo.

Anyway, if you are ok with that I can provide a small and quick PR adding this.

**Comment by uittorio** [comment]
thanks. I've added the template for bugs but not for features :)

**Comment by C0ZEN** [comment]
PR provided.
