### ISSUE TITLE
npm run install-types is slow

### ISSUE THREAD

**Issue by Manu1400** [Typescript-TDD/ts-auto-mock#396]
### Subject of the issue
The command `npm run install-types` on definitelyTypedTests directory run `git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git ../DefinitelyTyped` command but it's so slow.

### Your environment
* ts-auto-mock version: lasted

### Steps to reproduce
1. `cd definitelyTypedTests/`
2. `npm install` on definitelyTypedTests directory
3. `npm run install-types` to install/download types from definitelyTyped
4. Wait one minute with a xDSL internet
5. `Cmd + C` to kill the command (because it's too slow)

### Expected behavior
Prefer `git clone --depth 10 https://github.com/DefinitelyTyped/DefinitelyTyped.git ../DefinitelyTyped`

**Comment by Manu1400** [comment]
Like in https://github.com/microsoft/DefinitelyTyped-tools/blob/0cdd21e86d1fd9675fa91e8870ec7e88712d6734/packages/definitions-parser/src/git.ts#L34

**Comment by Manu1400** [comment]
In verbose mode: 
> Receiving objects:  59% (303435/508182), 302.25 MiB

**Comment by uittorio** [comment]
@Manu1400 thanks for opening this issue :) we'll fix that soon! I didn't know about --depth

**Comment by uittorio** [comment]
I've opened a PR. I've decided to use 1 instead of 10. Is there any reason why you've shown 10 in the example?

https://github.com/Typescript-TDD/ts-auto-mock/pull/399

**Comment by Pmyl** [comment]
PR #339 merged in master, @Manu1400 let me know if it does what you expect so I can close this issue

**Comment by uittorio** [comment]
Closing because is fixed :) Thanks again for the feedback!
