### ISSUE TITLE
Running test after compiling produces "ts_auto_mock_1.createMock is not a function" error

### ISSUE THREAD

**Issue by yosiawan** [Typescript-TDD/ts-auto-mock#402]
### Subject of the issue
Failed to mock on production build codes

### Your environment
        "ts-auto-mock": "^2.2.8",
        "typescript": "^3.7.4"
* node version: 12.3.1
* npm version: 6.9.0

### Steps to reproduce
- run ```npm build``` (runs ```jest```)
- run ```npm run test``` (runs ```tsc```)

Code before build
```
    const dmmyCtx = createMock<TContext>();
```
Code after build
```
    const dmmyCtx = ts_auto_mock_1.createMock();
```

### Expected behavior
ts auto mock runs without error and mock a type

### Actual behavior
The following error shows up
```
    TypeError: ts_auto_mock_1.createMock is not a function
```
Upon Inspecting the compiled code, ts_auto_mock_1.createMock() refers to this code
node-modules/ts-auto-mock/create-mock.d.ts
```
export declare function createMock<T extends object>(values?: DeepPartial<T>): T;
```

It seems that the code either doesn't compile correctly or points to a wrong type definition

**Comment by uittorio** [comment]
Hi @yosiawan. Thank you for reporting the issue. 

The code after build indicates that the ts-auto-mock transformer was not applied when compiling.

Could you share your test configuration? Do you have a repo you could share?

If you are not sure how to make sure that the transformer is added a compile time you can follow this guide.
https://typescript-tdd.github.io/ts-auto-mock/installation

**Comment by yosiawan** [comment]
Hi @uittorio , thank you for your reply. Sorry but I cannot share my repo. I have followed the guide in the link you provided with no luck, am I missing something or am I using incompatible version of dependencies? Here are my configs

tsconfig.json
```
{
    "compilerOptions": {
        "target": "ES2015",
        "module": "commonjs",
        "outDir": "./dist",
        "strict": true,
        "esModuleInterop": true,
        "baseUrl": "./",
        "plugins": [
            {
                "transform": "ts-auto-mock/transformer",
                "cacheBetweenTests": false
            }
        ]
    }
}
```
jest.config.js
```
module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    globals: {
        "ts-jest": {
            compiler: "ttypescript",
        },
        "jest": {
            "setupFiles": [
              "<rootDir>/config.ts"
            ]
          },
    },
};
```
package.json
```
"devDependencies": {
       "jest-ts-auto-mock": "^1.0.11",
        "@types/jest": "^26.0.3",
        "jest": "^26.1.0",
        "@types/body-parser": "^1.17.0",
        "@types/express": "^4.16.1",
        "@types/form-data": "^2.5.0",
        "@types/form-urlencoded": "^2.0.1",
        "@types/graphql-type-json": "^0.1.3",
        "@types/http-proxy": "^1.17.0",
        "@types/ioredis": "^4.14.7",
        "@types/lodash": "^4.14.147",
        "@types/node-fetch": "^2.5.4",
        "@types/passport": "^1.0.2",
        "@types/passport-oauth2": "^1.4.8",
        "@types/passport-oauth2-client-password": "^0.1.2",
        "@types/redis": "^2.8.15",
        "@types/request": "^2.48.4",
        "@types/url-join": "^4.0.0",
        "@types/uuid": "^3.4.5",
        "nodemon": "^1.19.4",
        "prettier": "^1.19.1",
        "ts-auto-mock": "^2.2.8",
        "ts-jest": "^26.1.1",
        "ts-node": "^8.1.0",
        "ttypescript": "^1.5.10",
        "typescript": "^3.7.4"
    },
```
jest-ts-auto-mock.config.json
```
{
    "jest": {
        "setupFiles": ["<rootDir>config.ts"]
    }
}

```

**Comment by uittorio** [comment]
Hi @yosiawan. i've tried to replicate your issue using your configuration but unfortunately is working.
I've notice one small details.


```
module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    globals: {
        "ts-jest": {
            compiler: "ttypescript",
        },
        "jest": {
            "setupFiles": [
              "<rootDir>/config.ts"
            ]
          },
    },
};
```


In this config the setupFiles is in the wrong object.
it should be like this

```
module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
   setupFiles: [
              "<rootDir>/config.ts"
            ],
    globals: {
        "ts-jest": {
            compiler: "ttypescript",
        }         
    },
};
```

Is your config file called jest.config.js?

**Comment by yosiawan** [comment]
Yes, my config file is jest.config.js and no I didn't have any other config in my package.json. I have fixed my config as you said, delete the build code, rebuild it, and ran the test again and it still won't compile into the right code.

**Comment by uittorio** [comment]
I think you need to add ts-auto-mock it as devDependency but I can see that your package.json already has it.

**Comment by uittorio** [comment]
Could you show me one of your test? I just need the import from ts-auto-mock and the creation of the mock.

**Comment by uittorio** [comment]
@yosiawan 

I don't know if is relevant but your code should be built as part of the jest run. If you build the code with just tsc it will not compile correctly. If you want to compile with the transformer you have to use 
```
ttsc
```

instead of 


```
tsc
```

Does it make sense?

**Comment by yosiawan** [comment]
Ah, that makes sense. Let me try switching tsc for ttsc.

**Comment by yosiawan** [comment]
Ah it worked perfectly ! I am really sorry this is a silly mistake on my end.

Thank you!

**Comment by uittorio** [comment]
@yosiawan No problem at all! I would be interested to understand why you need to run tsc first! there may be a use case that we want to document a bit better!

**Comment by yosiawan** [comment]
Do you mean why I run tsc before running my tests? It's because we would like to test our compiled code to be sure that the code will still run as intended after compiling it.

**Comment by uittorio** [comment]
@yosiawan for testing purposes ts-jest compiles the code for you. I believe running tsc is not necessary before running the tests.

**Comment by yosiawan** [comment]
Oh really? Alright then, I'll switch over to just running my tests.

Thanks again!
