### ISSUE TITLE
[Issue] Type instantiation is excessively deep and possibly infinite while using `createMock`

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#471]
### Subject of the issue

This is related to a type issue when using the `createMock` function with discord.js.
They landed a new version [12.3.0](https://github.com/discordjs/discord.js/releases/12.3.0) and there is an issue visible on [this project](https://github.com/Sonia-corporation/il-est-midi-discord/pull/758).

**Test:**

`createMock<Client>()`

Client is from `discord.js`.

**Error:**

`Type instantiation is excessively deep and possibly infinite.`

### Your environment
* ts-auto-mock version: 2.3.4
* typescript version: 3.9.7
* node version: 13.7.0
* npm version: 6.14.6

### Expected behavior
No error.

### Actual behavior
Type error.

**Comment by uittorio** [comment]
Hi @C0ZEN. Sorry to get back to you late, I had a busy week. I am looking into this issue and https://github.com/Typescript-TDD/ts-auto-mock/issues/464

**Comment by C0ZEN** [comment]
@uittorio no problem this is not blocking on my side so take your time.

**Comment by uittorio** [comment]
It looks like there is an issue on Typescript. I am not sure it is the same issue but It has been added to typescript 4.0.1 milestone https://github.com/microsoft/TypeScript/issues/34933.

**Comment by uittorio** [comment]
I've noticed that without the casting everything is working

**Comment by C0ZEN** [comment]
@uittorio nice catch.
As I said I am not in a hurry to update discord.js but can you tell me what is the best option here for me?
Wait that you come up with a solution - with the TypeScript error I suppose you will wait -, wait for TypeScript to come up with a solution or just add the `valueOf` like above?

**Comment by uittorio** [comment]
https://github.com/Typescript-TDD/ts-auto-mock/issues/464#issuecomment-674516498 I think this would be the best approach if you want to update to the new discord version

**Comment by uittorio** [comment]
This should be fixed now by 2.3.5.. @C0ZEN feel free to close it once you get the chance to confirm that is working :)

**Comment by C0ZEN** [comment]
@uittorio I will give it a try tonight and if all good I will close this PR.
Thanks for the fix.
