### ISSUE TITLE
intersection with typescript libs

### ISSUE THREAD

**Issue by uittorio** [Typescript-TDD/ts-auto-mock#5]
I wrote some test scenario with jasmine to simplify the explanation

```ts
describe('intersection with typescript lib', () => {
	type TypeIntersection = {} & Promise<string>;
		
	interface Intersection {
		a: TypeIntersection;
	}

	it('should be undefined', () => {
		const properties: Mock<Intersection> = createMock<Intersection>();
		expect(properties.a.then).toBeUndefined(); // it fail
	});
});

**Comment by Pmyl** [comment]
Tell me if I'm wrong, to solve this at some extent we just need to normalize the variable names to avoid `[Symbol.toStringTag]` to error as a name. The fact is that normally a `Promise` is not mocked entirely so probably it shouldn't happen here too.

This issue actually brings up a problem with intersection types when one part of the intersection is a function. That is going to either fail miserably in the same way as the `Promise` case or is just going to mock entirely the Function without using the MockFactory (jasmine, jest, etc).

Maybe we need to review how we handle intersection types?

**Comment by uittorio** [comment]
Yes, so the problem is how we are handling intersection types. Right now is using getPropertyOfTypes from typescript api, and that functionality try to fetch all the properties of a real Promise. We definitely have to solve Symbol.toStringTag and I have to make sure that the type is converted to our Promise before  converting it. Unfortunately the conversion of the Promise is not centralised yet

**Comment by Pmyl** [comment]
@uittorio I think this is already working. The behaviour is that if something comes from typescript types it ignores it completely.

Let me know if this can be closed

**Comment by uittorio** [comment]
We can ignore this issue with the assumption that we ignore typescript libs for intersections. If we are happy with that we can close it for now. If in the future we need the functionality we can open a new issue
