### ISSUE TITLE
createMockList() returns undefined when called with a passed-in function argument

### ISSUE THREAD

**Issue by ChrisKanaganayagam-AI** [Typescript-TDD/ts-auto-mock#595]
I have a bit of a weird issue when calling createMockList. Whenever I call createMockList with an argument passed into a function denoting how many of the objects I'd like to create, createMockList returns undefined. There are no issues if I hardcode the number in createMockList. Since a picture (or code in this case) might be worth a thousand words, here's something I quickly hacked together to highlight the issue:

```
import { createMockList } from 'ts-auto-mock';


export class Animal {
  numberOfLegs: number;
}

fdescribe('AnimalTest', () => {
  function createSpecificNumberOfMockAnimals(numberOfAnimals: number): Animal[] {
    return createMockList<Animal>(numberOfAnimals);
  }

  function createMockAnimals(): Animal[] {
    return createMockList<Animal>(2);
  }

  it('should create animals with specific number', async () => {
    const mockAnimals = createSpecificNumberOfMockAnimals(3);
    console.log(mockAnimals[0]); // log says undefined
    expect(mockAnimals.length).toEqual(3); // test failure saying "Error: Expected 0 to equal 3."
  });

  it('should create animals without specifying number', async () => {
    const mockAnimals = createMockAnimals();
    console.log(mockAnimals[0]); // log outputs an animal with a random number of legs
    expect(mockAnimals.length).toEqual(2); // test passes
  });
});
```

### Environment
* ts-auto-mock version: 2.6.4
* typescript version: 3.8.3
* node version: 10.13.0
* npm version: 6.4.1
* ts-patch: 1.3.0
* angular: 9.1.12
* karma: 4.4.1
* jasmine-core: 3.4.0

### Steps to reproduce
If you are able to run the two test cases above, the first test case fails. Second test case passes.

### Expected behavior
We should be able to pass in an arg into a function to specify how many of an object to create with createMockList.

### Actual behavior
Whenever an arg is passed into a function to specify the number, createMockList() returns undefined.

**Comment by uittorio** [comment]
hi @ChrisKanaganayagam-AI ! Thanks for reporting the issue :) 

I confirm that it's an issue. We currently try to understand the number using the typescript AST. In the scenario where you send a value from another function, it doesn't recognize the 'number'. 

This is the code that does not translate correctly the number: [here](https://github.com/Typescript-TDD/ts-auto-mock/blob/master/src/transformer/mock/mock.ts#L82) and [here](https://github.com/Typescript-TDD/ts-auto-mock/blob/master/src/transformer/mock/mock.ts#L29)

We'll keep you update.. it shouldn't be too difficult finding the value :)

**Comment by ChrisKanaganayagam-AI** [comment]
Thanks for looking into this so quickly @uittorio . Much appreciated! :)

**Comment by uittorio** [comment]
Just released @ChrisKanaganayagam-AI !! 💚  💚  💚  💚  💚

**Comment by ChrisKanaganayagam-AI** [comment]
Thank you very much @uittorio . Much appreciated sir!
