### ISSUE TITLE
[Idea] Add a bug or a feat label on issues automatically

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#599]
**Describe the solution you'd like**
When a new issue is created, add automatically a `bug` or a `feat` label based on AI and the issue content.
A small yet useful information visible without checking the whole issue content.
Also a great way to have statistics about the kind of issues opened via GitHub labels. 

P.S: yeah I know that there is two templates so the information is already there but labels are life.

**Additional context**
Done it into another project so just tell me if you are okay with this and I will provide a fast and small PR.

**Comment by uittorio** [comment]
hey @C0ZEN. I've never done this before, feel free to open a PR! sorry for replying so late, just cleaning up old issues.
