### ISSUE TITLE
[Idea] Integrate with Contributors to show an hall of fame from contributors

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#600]
**Describe the solution you'd like**
Because most people doing open source contribution like a bit of fame.
Also because hall of fame is cool.
Just add an hall of fame at the bottom of the readme.

**Additional context**
Done it into another project so just tell me if you are okay with this and I will provide a fast and small PR.

**Comment by uittorio** [comment]
I like the idea!!! Can we also include the profile picture of the users that contributed to the repo?

**Comment by C0ZEN** [comment]
@uittorio yeah, the profile picture will be included.
Take a look here https://github.com/all-contributors/all-contributors if you want more information.
I will provide a PR right away.
