### ISSUE TITLE
createMockList doesn't accept variable as parameter

### ISSUE THREAD

**Issue by BrunoBeraudPW** [Typescript-TDD/ts-auto-mock#603]
### Subject of the issue
The createMockList function does not seem to accept a variable as a parameter of the array size.

### Your environment
* ts-auto-mock version: 2.6.4
* typescript version: 3.7.5
* node version: 12.15.0
* npm version: 6.13.4

Used in angular 9.1.12 context with jasmine  3.5.14

### Steps to reproduce
    const nb = 2;
    interface Person {
      id: string;
    }
    const mockList = createMockList<Person>(nb);
    console.log(mockList.length);

When I put directly the value 2 in the function it's working

### Expected behavior
Length should be 2

### Actual behavior
Length is 0, I have an empty array

**Comment by Pmyl** [comment]
This is fixed in version 2.6.5, try to update the library and let me know

**Comment by BrunoBeraudPW** [comment]
Yes in deed perfect, thank you and sorry for the inconvenience
