### ISSUE TITLE
Unable to mock opaque type 

### ISSUE THREAD

**Issue by BrunoBeraudPW** [Typescript-TDD/ts-auto-mock#604]
### Subject of the issue
Hello, 
I found that auto-mock are not able to mock opaque type.
It's too bad because opaque type could be really an useful practice in typescript application
When I will have more time I'll try to found a solution to fix that.
Thank you for reading !

### Your environment
* ts-auto-mock version: 2.6.5
* typescript version: 3.7.5
* node version: 12.15.0
* npm version: 6.13.4

### Steps to reproduce

    type A = string & { type: 'A' }
    interface I {
       a: A
    }

    const i = createMock<I>()

    console.log(i.a);

### Expected behavior
console.log should be a mocked string

### Actual behavior
console.log is null

**Comment by uittorio** [comment]
Hi @BrunoBeraudPW . Thank you for reporting the issue. We default any intersection types with undefined. When it is useful to have string & {} (any interface) ? opaque type like `type B = number` it will work.

**Comment by BrunoBeraudPW** [comment]
Hey, I use this implementation to have a strong Type protection for the arguments or return of my methods and classes


    type A = string & {type: 'a'};
    const test = (a: A): void => {}
    const myString  = "s";
    test(myString); // <= will raise an error
----------------------------------------
    type B = string;
    const test = (a: B): void => {}
    const myString = "s";
    test(myString); // <= will be ok :(

**Comment by uittorio** [comment]
I've only used opaque types once, i am not realy expert. Can you provide the actual implementation if the type that you are using? I want to understand how we should build the mock :) thanks!

**Comment by uittorio** [comment]
Nevermind, i've found an example, i'll update this issue this weekend :)

**Comment by BrunoBeraudPW** [comment]
Thank for your reactivity !

(My implementation is that 

      type Opaque<K, T> = T & { type: K };
      export type Sku = Opaque<'Sku', string>;
)

**Comment by Pmyl** [comment]
@BrunoBeraudPW what would you expect the variable to be, a string or an object with "type" property?
Since the library generates data we need to understand what is actually a piece of data that we need to create in Javascript.

Is this opaque type a hack while waiting for [this Typescript feature](https://github.com/Microsoft/TypeScript/issues/202)?

**Comment by Pmyl** [comment]
I have an idea... you can make this work using the `registerMock`.
Basically you register the opaque type to always be mocked in your own way:
```ts
// Somewhere
type Opaque<K, T> = T & { type: K };
export type Sku = Opaque<'Sku', string>;

// In the common test file (webpack: context.ts, mocha: tsnode.js, etc)
registerMock<Sku>(() => 'Sku'); // now every property with Sku type will be mocked as 'Sku' string
```

I know it's not super ideal because for every opaque type you have to have a `registerMock` but if you have just a small amount this could be a solution

**Comment by BrunoBeraudPW** [comment]
@Pmyl Yeah it's exactly this feature (nominal type)
Very good point for registerMock, I wasn't aware that was existing :D
It's going to help me out.

After thinking, I think it's impossible to have a generic behavior to manage opaque type in ts-auto-mock because precisely, we could have many implementation of opaque type.
Otherwise, you could define an unique implementation of opaque type which will be supported by ts-auto-mock

But regardless of the implementation, the logic remains the same: 
Have to "unOpaque" the opaque type 
For my implementation it will be done by this kind of type :

      type unOpaque <Type> = Type extends Opaque<any, infer T> ? T : Type;

And then cast at the end the value generated "as OpaqueType"

By example :

      registerMock<T>(() => randomGenerator<unOpaque<T>>() as T);

And it will continue to works for unopaque type
I don't find the time yet to check the real implementation of createmock so the example is, I know, not accurate.
But you have the idea.

**Comment by Pmyl** [comment]
@BrunoBeraudPW I'm adding a feature that will allow you to configure `registerMock` only once to solve the Opaque type problem: #605 
I hope it helps

**Comment by uittorio** [comment]
@Pmyl thanks for looking into the issue and finding a quick nice solution :)

**Comment by BrunoBeraudPW** [comment]
Damn you rock ! 
Thx a lot for this quick feature !
I think we can close the ticket

**Comment by BrunoBeraudPW** [comment]
Ooops, so it's work well but I'm stuck in an another problem, I have an error when I use registerMock in a "common file" :

     An error was thrown in afterAll
     TypeError: ts_auto_mock_repository__WEBPACK_IMPORTED_MODULE_0__.ɵRepository.instance.getFactory(...) is not a function
     at Object.get (http://localhost:9876/_karma_webpack_/main.js:19918:174)
     at Eo (http://localhost:9876/_karma_webpack_/node_modules/ts-auto-mock/merge/index.js:1:54254)

It's not related with your feature (I tried to downgrade the version I have still this error)
I'm using angular app 9.1.11, with ts-patch 1.2.5 and jasmine 3.6.0
tsconfig.json:

      "plugins": [
           { "transform": "ts-auto-mock/transformer", "debug": true, "cacheBetweenTests": false, "features": ["random"] }
        ]

The rest of the configuration is quite common

I tried to use registerMock in the test.ts file which is the main entry-point file using by webpack in angular.json for the jasmine tests.
It seem that it's throw this error when I'm trying to use registerMock with a type which will not be used in the file

Maybe you have an idea (if it's a common error) ? 
If not I can create a repository with all my configuration.

Thank again !

**Comment by uittorio** [comment]
Hi, could you try again with the cacheBetweenFiles option enabled?

**Comment by uittorio** [comment]
If you are using angular with the entry test file the cache should work correctly

**Comment by BrunoBeraudPW** [comment]
In deed it's working now, thank you all !

**Comment by BrunoBeraudPW** [comment]
Hi, sorry me again...

It seem that since I have turned on the cache, I have an issue with the hotreload for karma test
Seem to be related to https://github.com/Typescript-TDD/ts-auto-mock/issues/105
I have the same error than before, but only when is triggered the hotreload :

 An error was thrown in afterAll
 TypeError: ts_auto_mock_repository__WEBPACK_IMPORTED_MODULE_0__.ɵRepository.instance.getFactory(...) is not a function
 at Object.get (http://localhost:9876/_karma_webpack_/main.js:19918:174)
 at Eo (http://localhost:9876/_karma_webpack_/node_modules/ts-auto-mock/merge/index.js:1:54254)

I don't have this error "the first" execution.

I see you said you had in mind a solution to improve your cache system, had you been able to implement it?

It's happen when I try to use createMock function, do you know what this error means?

Thank again !

**Comment by uittorio** [comment]
Hey, yep. It looks like improving the caching system may solve that issue. Do you mind opening a bug with the results you have? I would like to keep a bug open as a reminder :). For your particular example you could try to disable the cache and move the registerMock inside each test file that needs that mock, It's not a great solution but it may works.

**Comment by BrunoBeraudPW** [comment]
Yes no problem of course, I'll do that soon as possible with a repo to reproduce the problem
