### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by iurevych** [Typescript-TDD/ts-auto-mock#619]
Hello, I went through the whole tutorial but still can't get it to work, it throws an error when running Jest tests:
```
hey, it looks like ts-auto-mock is not configured correctly! You can find the instructions here https://typescript-tdd.github.io/ts-auto-mock/installation.
      If you need further assistance feel free to drop a message on slack. (link at the bottom of https://typescript-tdd.github.io/ts-auto-mock)

       9 |
      10 | describe('<CartItem />', () => {
    > 11 |   const cartItem: CartItem = createMock<CartItem>()
         |                              ^
      12 |
      13 |   describe('Render', () => {
      14 |     it('should have price', () => {

      at r.createMock (node_modules/ts-auto-mock/index.js:1:606)
      at Suite.<anonymous> (tests/app.test.tsx:11:30)
      at Object.<anonymous> (tests/app.test.tsx:10:1)
```

Here is the test itself https://github.com/iurevych/jest-ts-auto-mock-playground/blob/main/tests/app.test.tsx. I created this fresh new repo to isolate the environment.

Please help, I'm trying to automate TS interface mocks.

**Comment by uittorio** [comment]
Hi @iurevych !  How are you running your tests? It looks like there is an additional jest config that is not using ts-jest to transpile the typescript file. Also your jest.config.js is not importing jest-ts-auto-mock. This is not going to fix the issue you are having. I think the tests you are running are not using the configuration from the package.json file.

**Comment by uittorio** [comment]
HI @iurevych , sorry to get back to you so late. I've clone your repository and I've realised that you are also using a jest.config.js file. That file is overriding the jest config in the package json. You can either remove the jest configfile or add the correct configuration to that file! I hope this helps!

**Comment by uittorio** [comment]
Closing this bug because it was a configuration issue, and again sorry to look into this so late :).

**Comment by carlos89pc** [comment]
I have the same problem, have you found the solution? @iurevych
