### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#699]
### Subject of the issue
I replaced all the `createMock` by `createHydratedMock` and now I have a bunch of failing tests.

Here is a stack trace issue example:

```
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded
        at Array.map (<anonymous>)

      at node_modules/ts-auto-mock/transformer/index.js:1:54686
          at Array.map (<anonymous>)
      at Object.getExpressionForAllGenerics (node_modules/ts-auto-mock/transformer/index.js:1:54549)
      at f (node_modules/ts-auto-mock/transformer/index.js:1:75116)
      at Object.t.GetMockFactoryCall (node_modules/ts-auto-mock/transformer/index.js:1:75577)
      at Object.t.GetTypeReferenceDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:51148)
      at Object.t.GetDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:10993)
      at Object.t.GetPropertyDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:39118)
      at Object.t.GetDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:11380)
```

### Your environment
* ts-auto-mock version: 3.1.3
* typescript version: 4.1.5
* node version: 14.3.0
* npm version: 6.14.12

### Steps to reproduce
Well, this is complicated because it's not a particular test which fails, it's the whole run on a given file.
Do you have any clue on the reason?
Because it's strange that everything works for one method and not the other one.
If you have no clue at all, I can try to find a more precise issue for you to debug.
Let me know, thanks!

### Expected behavior
No error.

### Actual behavior
Some errors.

https://github.com/Sonia-corporation/sonia-discord/issues/1374

**Comment by uittorio** [comment]
Hey!'

Another maximum call stack size exceeded.

Hydrated mock will automatically mocks the non required fields. It could be that one of the interfaces that you are moking has a feature that we dont support yet.


Can you try and use debug console in the transformer options and see if you see more useful information?
We should definitely improve the tracing.


Do you have a branch I can try?

If none of the above helps you may have to try them one by one.

**Comment by C0ZEN** [comment]
I took a look but honestly I have no idea on what to look to help you identify the culprit.
I created a [PR with the hydrated mocks](https://github.com/Sonia-corporation/sonia-discord/pull/1383) if you wish to take a look.
Thanks!

**Comment by uittorio** [comment]
I ll have a look!! Hopefully it will be fixed soon!

**Comment by C0ZEN** [comment]
@uittorio don't worry too much it's not a priority for me but thanks anyway, good luck!

**Comment by uittorio** [comment]
@C0ZEN just to let you know I found the bug

Unfortunately when creating an hydratedMock for a recursive interface that has a union type of (A | null) it doesn't work as expected

```
interface A {
   prop: A | null
} 

```

I have a fix in mind, I will create a PR ASAP.

**Comment by C0ZEN** [comment]
@uittorio ok thanks, nice catch!

**Comment by uittorio** [comment]
really late but here is the fix. https://github.com/Typescript-TDD/ts-auto-mock/pull/736

**Comment by C0ZEN** [comment]
@uittorio thanks!

**Comment by uittorio** [comment]
This is now live! I havent tested your particular branch with the new version! Hopefully it was the only issue!

**Comment by C0ZEN** [comment]
Indeed, the fix was enough, thanks!
I just have to fix 46 failing tests, seems a lot but could be simply related to the flakiness introduced by the hydrated mocks.
