### ISSUE TITLE
Hydrated mock with undefined object values as parameter

### ISSUE THREAD

**Issue by C0ZEN** [Typescript-TDD/ts-auto-mock#746]
### Subject of the issue
I noticed on subtle change between the `createMock` and `createHydratedMock` functions.
Following my last comment https://github.com/Typescript-TDD/ts-auto-mock/issues/699.
Should fix https://github.com/Sonia-corporation/sonia-discord/pull/1383

### Your environment
* ts-auto-mock version: 3.2.1
* typescript version: 4.2.4
* node version: 14.17.0
* npm version: 7.12.1
* jest-ts-auto-mock: 2.0.0

### Steps to reproduce

No problem, the features will stay undefined.
```typescript
channel = createMock<IFirebaseGuildChannelV2>({
  features: undefined,
  id: `dummy-id`,
  version: FirebaseGuildChannelVersionEnum.V2,
});
```

The features will have random values.
```typescript
channel = createHydratedMock<IFirebaseGuildChannelV2>({
  features: undefined,
  id: `dummy-id`,
  version: FirebaseGuildChannelVersionEnum.V2,
});
```

### Expected behaviour
Same behaviour between `createMock` and `createHydratedMock` functions which replace the `undefined` value as expected (so `createMock` is better IMO).

### Actual behaviour
The `createHydratedMock` function will ignore the given object value if `undefined` instead of using the value to fill the mock.

**Comment by Pmyl** [comment]
this should be easy to solve, I'll take care of this

**Comment by Pmyl** [comment]
PR open, just waiting for @uittorio to review it hoping he likes it 🤞
