### ISSUE TITLE
Prevent repetition of emitted code when mocking extended/implemented interfaces

### ISSUE THREAD

**Issue by Pmyl** [Typescript-TDD/ts-auto-mock#8]
As a user I want to be able to run my test suit with more performance as possible without code repetition emitted by the transformer.

**Use case**
Given the case where we have an interface and an implemented class:
```ts
interface IPerson {
  firstName: string;
  lastName: string;
}

class PersonImpl implements IPerson {
  public firstName: string;
  public lastName: string;
  public age: number;
}
```
if I mock Person in one spec and IPerson in another spec I ends up with this (more or less) emitted code:
```ts
// factory for IPerson mock
repository.register('mockFactory-i-person', (function(){
  var firstName, lastName;
  return {
    get firstName() { return firstName || (firstName = '') },
    set firstName(_firstName) { firstName = _firstName },
    get lastName() { return lastName || (lastName = '') },
    set lastName(_lastName) { lastName = _lastName }
  }
}))

// factory for PersonImpl mock
repository.register('mockFactory-person-impl', (function(){
  var firstName, lastName, age;
  return {
    get firstName() { return firstName || (firstName = '') },
    set firstName(_firstName) { firstName = _firstName },
    get lastName() { return lastName || (lastName = '') },
    set lastName(_lastName) { lastName = _lastName },
    get age() { return age || (age = '') },
    set age(_age) { age = _age }
  }
}))
```

The emitted code contains a repetition that could affect the performance in the long run.

**Proposed solution**
I don't have a complete solution but the idea is to treat extension (and intersection between objects) using some sort of Object.assign to reuse already existing factories.
The final emitted code would be on the line of:
```ts
// factory for IPerson mock
repository.register('mockFactory-i-person', (function(){
  var firstName, lastName;
  return {
    get firstName() { return firstName || (firstName = '') },
    set firstName(_firstName) { firstName = _firstName },
    get lastName() { return lastName || (lastName = '') },
    set lastName(_lastName) { lastName = _lastName }
  }
}))

// factory for PersonImpl mock
repository.register('mockFactory-person-impl', (function(){
  var age;
  return assignWorkingForGetSet({
      get age() { return age || (age = '') },
      set age(_age) { age = _age }
    },
    repository.get('mockFactory-i-person')
  );
}))
```

**Comment by uittorio** [comment]
To implement this feature we would have to merge two different mocks.
Any merge functionality will have to check if a field exist into an object. This will cause trigger getters of our internal mock. If the getter is a reference to a mock that has recursion it will cause Maximum call stack.

Feel free to close the issue if you are happy with the conclusion

Example
```ts
interface A {
 mySelf: A
}

interface B extends A {
   bProperty: string;
}

repository.register('A', (function(){
  var __mySelf;
  return {
      get mySelf() { return __mySelf || (__mySelf = repository.get('A')) },
      set mySelf(_mySelf) { mySelf= _mySelf}
    },
  );
}))

repository.register('B', (function(){
  var __bProperty;
  var mock;

  mock = {
      get bProperty() { return __bProperty || (__bProperty = '') },
      set bProperty(_bProperty) { bProperty = _bProperty }
  };
  return  mergeFunctionality(mock, repository.get('A')) // this will cause the error because some property mySelf of A is recursive
  );
}))

```

**Comment by Pmyl** [comment]
I have another idea to solve this that won't trigger the getters, let's keep this open at low priority right now

**Comment by Pmyl** [comment]
@uittorio I still have an idea on how to do it but I think it's not worth it from every angle.
Not worth it because other features are definitely more important.
Not worth it because it doesn't really improve performance.
Not worth it because it will probably affect the performance negatively (in my solution I would trade lines of code for run time).

I'm closing this, if we actually see people having performance issues with this then we can reopen it.
