### ISSUE TITLE
Error in install instructions on Github Pages website

### ISSUE THREAD

**Issue by cruxicheiros** [Typescript-TDD/ts-auto-mock#974]
### Subject of the issue
On [this page](https://typescript-tdd.github.io/ts-auto-mock/installation#jest--ts-jest--ts-patch) there is a typo that stops the code from working.

### What the problem is
In step 2 the instructions are to insert this into `tsconfig.json`
```json
...
  "compilerOptions": {
    ...
    "plugins": [0
      {
        "transform": "ts-auto-mock/transformer",
        "cacheBetweenTests": false
      }
    ]
    ...
  }
  ...
```

### What it should be
```json
...
  "compilerOptions": {
    ...
    "plugins": [
      {
        "transform": "ts-auto-mock/transformer",
        "cacheBetweenTests": false
      }
    ]
    ...
  }
  ...
```

The fix is to remove the stray 0.

I would have made a PR but couldn't work out where the website source was.

**Comment by uittorio** [comment]
Thank you @cruxicheiros. I will find some time during the weekend to fix it. This is the file if you want to open a pr. https://github.com/Typescript-TDD/ts-auto-mock/blob/master/ui/src/views/installation.mdx

**Comment by uittorio** [comment]
this is now fixed. Feel free to refresh the page and check :) 

Thank you for spotting the issue! https://typescript-tdd.github.io/ts-auto-mock/installation#jest--ts-jest--ts-patch

**Comment by cruxicheiros** [comment]
No worries! Thanks for responding to the issue. It looks fixed now :)
